set(target_libraries
  CppMicroServices
  CppMicroServices_LIBRARIES
  CTKCore
  CTKPluginFramework
  mbilog_LIBRARIES
  itkCommon_LIBRARIES
  mitkCore_LIBRARIES
  qtsingleapplication_LIBRARIES
  Poco::Util
  )
